name: Docker Keyloak

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '22 7 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: icr.io
  # Use ICR_NAMESPACE for main branches else use github repo name for PRs
  IMAGE_NAME: ${{ secrets.ICR_NAMESPACE || github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ICR_USERNAME }}
          password: ${{ secrets.ICR_APIKEY }}

      - name: Set variables
        working-directory: ./keycloak-infra/keycloak
        run: |
          KEYCLOAK_VERSION=$(cat KEYCLOAK_VERSION)
          echo "KEYCLOAK_VERSION=$KEYCLOAK_VERSION" >> $GITHUB_ENV

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/keycloak
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{raw}},suffix=-${{ env.KEYCLOAK_VERSION }}
      
      - name: Populate the theme content
        id: theme
        run: |
          cd ./keycloak-infra/keycloak
          make sync-theme

#      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: ./keycloak-infra/keycloak
          dockerfile: ./keycloak-infra/keycloak/Dockerfile
          build-args: KEYCLOAK_BASE_IMAGE=quay.io/keycloak/keycloak:${{ env.KEYCLOAK_VERSION }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
#            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:{{ env.RELEASE_VERSION }}-${{ env.KEYCLOAK_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Scan image (license only)
        uses: ./license_scan.yml
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/keycloak
          tag: ${{ github.sha }}
          fail-on-vuln: "true"
